export interface equiposCreacionDTO{
    PRO_ID:number,
    PRO_MARCA: string,
    PRO_FECHA_INGRESO: Date,
    PRO_MODELO: string,
    PRO_SERIAL: string,
    PRO_COD_ACTIVO: string,
    PRO_CPU: string,
    PRO_GEN: string,
    PRO_NUC: string,
    PRO_ASIGNADO: string,
    PRO_USO: string,
    PRO_USER_WIN: string,
    PRO_WIN_CON: string,
    PRO_NOMBRE_PRODUCTO: string,
    PRO_DIRECCION_IP: string,
    PRO_ANYDESK: string,
    PRO_CON_ANYDESK: string,
    PRO_SO: string,
    PRO_OFFICE: string,
    PRO_FILESERVER: string,
    PRO_ANTIVIRUS: boolean
}

export interface equipoDTO{
    PRO_ID:number,
    PRO_MARCA: string,
    PRO_FECHA_INGRESO: Date,
    PRO_MODELO: string,
    PRO_SERIAL: string,
    PRO_COD_ACTIVO: string,
    PRO_CPU: string,
    PRO_GEN: string,
    PRO_NUC: string,
    PRO_ASIGNADO: string,
    PRO_USO: string,
    PRO_USER_WIN: string,
    PRO_WIN_CON: string,
    PRO_NOMBRE_PRODUCTO: string,
    PRO_DIRECCION_IP: string,
    PRO_ANYDESK: string,
    PRO_CON_ANYDESK: string,
    PRO_SO: string,
    PRO_OFFICE: string,
    PRO_FILESERVER: string,
    PRO_ANTIVIRUS: boolean
}